<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Запускает сборку bundleconfig.json (site.css -> site.min.css, site.js -> site.min.js) при билде -->
    <PackageReference Include="BuildBundlerMinifier" Version="3.2.449" />
  </ItemGroup>

</Project>
